changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: New features ✨
      labels:
        - ":sparkles: enhancement"
    - title: Fixes ✅
      labels:
        - ":bug: bug"
    - title: Other Changes
      labels:
        - '*'
