name: Build, test and check format

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - uses: oven-sh/setup-bun@v2

      - run: yarn install --immutable

      - name: Build package
        run: yarn build

      - name: Test the package
        run: yarn test

      - name: Check file formatting
        run: yarn format:check

      - name: pkg.pr.new
        run: npx pkg-pr-new publish
